package com.iot.building.space.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.iot.building.space.vo.LocationReq;
import com.iot.building.space.vo.LocationResp;

public interface LocationMapper {
	
	
    @Select(
			"select                               " +
			"id,							      " +
			"name,							      " +
			"icon,							      " +
			"org_id as orgId,					  " +
			"tenant_id as tenantId                " +
			"from location      				  " 
    		)
    public List<LocationResp> getAll();
    
    @Select(
    		"<script>                                     " +
    				"select                               " +
    				"id,							      " +
    				"name,							      " +
    				"icon,							      " +
    				"org_id as orgId,					  " +
    				"tenant_id as tenantId                " +
    				"from location       				  " +
    				"where 1=1 						      " +
    				"<if test=\"id != null\">			  " +
    				"and id=#{id}				          " +
    				"</if>							      " +
    				"<if test=\"name != null\">		  " +
    				"and name=#{name}		      " +
    				"</if>							      " +
    				"<if test=\"tenantId != null\">	  " +
    				"and tenant_id=#{tenantId}			  " +
    				"</if>							      " +
    				"<if test=\"orgId != null\">	  " +
    				"and org_id=#{orgId}			  " +
    				"</if>							      " +
    				"<if test=\"icon != null\">	  " +
    				"and icon=#{icon}		  " +
    				"</if>							      " +
    				"</script>"
    		)
    public List<LocationResp> findLocationByCondition(LocationReq locationReq);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_device
     *
     * @mbggenerated
     */
    @Insert({
                    "insert into location (" ,
                    "				id, " ,
                    "				name, " ,
                    "				icon, " ,
                    "				create_time, " ,
                    "				org_id, " ,
                    "				tenant_id) values(" ,
                    "				#{id}, " ,
                    "				#{name}, " ,
                    "				#{icon}, " ,
                    "				#{createTime}, " ,
                    "				#{orgId}, " ,
                    "				#{tenantId} )" 
    })
    int save(LocationReq locationReq);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_device
     *
     * @mbggenerated
     */
    @Update({
            "<script> " +
                    "update location " +
                    "		<set> " +
                    "			<if test=\"creatTime != null\"> " +
                    "				create_time = #{creatTime}, " +
                    "			</if> " +
                    "			<if test=\"name != null\"> " +
                    "				name = #{name}, " +
                    "			</if> " +
                    "			<if test=\"icon != null\"> " +
                    "				icon = #{icon}, " +
                    "			</if> " +
                    "			<if test=\"tenantId != null\"> " +
                    "				tenant_id = #{tenantId}, " +
                    "			</if> " +
                    "		</set> " +
                    "		where id = #{id}" +
                    "</script>                                                        "
    })
    int update(LocationReq locationReq);

    /**
     * 删除关系
     *
     * @mbggenerated
     */
    @Delete({
            "delete from " +
                    "		location " +
                    "		where id = #{id}  "
    })
    int delete(Long id);
}