package com.iot.shcs.space.vo;

import java.util.Date;
import java.util.List;
import java.util.Map;

public class SpaceDeviceResp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.last_update_date
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.space_id
     *
     * @mbggenerated
     */
    private Long spaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.location_id
     *
     * @mbggenerated
     */
    private Long locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.device_category_id
     *
     * @mbggenerated
     */
    private Long deviceCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_device.status
     *
     * @mbggenerated
     */
    private String status;

    private String position;

    private Long tenantId;

    private Long deviceTypeId;

    private Integer order;
    
    private Long productId;
    
    private Long businessTypeId;
    
    private List<Map<String, Object>> spaceInfoMapList;
    
    public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getDeviceTypeId() {
        return deviceTypeId;
    }

    public void setDeviceTypeId(Long deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String postion) {
        this.position = postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_device.id
     *
     * @return the value of space_device.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.id
     *
     * @param id the value for space_device.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_device.device_id
     *
     * @return the value of space_device.device_id
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.device_id
     *
     * @param deviceId the value for space_device.device_id
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_device.space_id
     *
     * @return the value of space_device.space_id
     * @mbggenerated
     */
    public Long getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.space_id
     *
     * @param spaceId the value for space_device.space_id
     * @mbggenerated
     */
    public void setSpaceId(Long spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_device.location_id
     *
     * @return the value of space_device.location_id
     * @mbggenerated
     */
    public Long getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.location_id
     *
     * @param locationId the value for space_device.location_id
     * @mbggenerated
     */
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_device.device_category_id
     *
     * @return the value of space_device.device_category_id
     * @mbggenerated
     */
    public Long getDeviceCategoryId() {
        return deviceCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.device_category_id
     *
     * @param deviceCategoryId the value for space_device.device_category_id
     * @mbggenerated
     */
    public void setDeviceCategoryId(Long deviceCategoryId) {
        this.deviceCategoryId = deviceCategoryId == null ? null : deviceCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_device.status
     *
     * @param status the value for space_device.status
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

	public Long getBusinessTypeId() {
		return businessTypeId;
	}

	public void setBusinessTypeId(Long businessTypeId) {
		this.businessTypeId = businessTypeId;
	}

	public List<Map<String, Object>> getSpaceInfoMapList() {
		return spaceInfoMapList;
	}

	public void setSpaceInfoMapList(List<Map<String, Object>> spaceInfoMapList) {
		this.spaceInfoMapList = spaceInfoMapList;
	}

}