REPLACE INTO `iot_db_system`.`sys_db_version` (`version`, `version_desc`) VALUES ('2018.09.30.07', '1、新增app打包2、语言接入商品及翻译');

REPLACE INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('10', '4', '0010', 'goods:googleyuyinfuw', NULL, 'Arnoo helps you to connect your product with Google Assistant which enables to control products by Google Assistant.', '3', '1', '8.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
REPLACE INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('11', '4', '0011', 'goods:amazonyuyinfuw', NULL, 'Arnoo helps you to connect your product with Amazon Alexa which enables to contro products by Amazon Alexa.', '3', '1', '8.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');

REPLACE INTO `iot_db_system`.`sys_dict_item` (`type_id`, `item_id`, `item_name`, `item_desc`, `item_sort`) VALUES ('2', '4', 'dict_item:yuyinjieru', '语音控制接入', '4');

REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('439', 'zh_CN', 'goods:googleyuyinfuw', 'Assistant语音接入', NULL, '2018-09-04 08:17:48', NULL, '2018-09-04 08:17:48', 'valid');
REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('440', 'en_US', 'goods:googleyuyinfuw', 'Google Assistant Access', NULL, '2018-09-04 16:14:10', NULL, '2018-09-04 16:14:16', 'valid');
REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('441', 'zh_CN', 'goods:amazonyuyinfuw', 'Alexa语音接入', NULL, '2018-09-04 16:14:10', NULL, '2018-09-04 16:14:16', 'valid');
REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('442', 'en_US', 'goods:amazonyuyinfuw', 'Amazon Alexa Access', NULL, '2018-09-04 16:14:10', NULL, '2018-09-04 16:14:16', 'valid');
REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('443', 'zh_CN', 'dict_item:yuyinjieru', '语音控制接入', NULL, '2018-09-04 08:29:15', NULL, '2018-09-04 08:29:15', 'valid');
REPLACE INTO `iot_db_system`.`lang_info` (`id`, `lang_type`, `lang_key`, `lang_value`, `create_by`, `create_time`, `update_by`, `update_time`, `is_deleted`) VALUES ('444', 'en_US', 'dict_item:yuyinjieru', 'Voice Control Service', NULL, '2018-09-04 08:28:55', NULL, '2018-09-04 08:28:55', 'valid');