replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('1', '2', '0001', 'goods:wififangan', 'plan_wifi', NULL, NULL, '3', '0.25', 'USD', '0', '1', '2018-07-03 11:07:27', '2018-07-03 11:07:31', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('2', '2', '0002', 'goods:lanyafangan', 'plan_bluetooth', NULL, NULL, '3', '0.25', 'USD', '0', '2', '2018-07-03 11:07:27', '2018-07-03 11:07:31', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('3', '2', '0003', 'goods:wangguanfangan', 'plan_gateway', NULL, NULL, '3', '0.25', 'USD', '1', '3', '2018-07-03 11:07:27', '2018-07-03 11:07:31', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('4', '2', '0004', 'goods:IPCfangan', 'plan_ipc', NULL, NULL, '3', '0.25', 'USD', '0', '4', '2018-07-03 11:07:27', '2018-07-03 11:07:31', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('5', '3', '0005', 'goods:appdabaofuw', NULL, 'Only one APP per official package is built. Payment will be followed up by someone, and there is a message notification, you can download and publish to the major application platforms.', '1', '1', '8.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('6', '0', '0006', 'goods:quanshiluying', NULL, 'Continuous recording of 7 days video(event trigger sign) All video storage service for 30 days', '7', '5', '30.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('7', '1', '0007', 'goods:300shijianluying', NULL, 'Continuous recording of 300 events video(event trigger sign) All video storage service for 30 days', '300', '4', '3.00', 'USD', '0', '2', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('8', '1', '0008', 'goods:600shijianluying', NULL, 'Continuous recording of 600 events video(event trigger sign) All video storage service for 30 days', '600', '4', '6.00', 'USD', '0', '3', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('9', '1', '0009', 'goods:1000shijianluying', NULL, 'Continuous recording of 1000 events video(event trigger sign) All video storage service for 30 days', '1000', '4', '8.00', 'USD', '0', '4', '2018-07-03 11:22:56', '2018-07-03 11:23:00', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('10', '4', '0010', 'goods:googleyuyinfuw', 'icon-com_icon_permission_GoogleAssistant', 'goods:googleyuyinfuw:desc', '3', '1', '8.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-11-14 09:13:18', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('11', '4', '0011', 'goods:amazonyuyinfuw', 'icon-com_icon_permission_Alexa', 'goods:amazonyuyinfuw:desc', '3', '2', '8.00', 'USD', '0', '1', '2018-07-03 11:22:56', '2018-11-14 09:13:18', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('12', '4', '0012', 'goods:siriAccess', 'icon-com_icon_permission_Siri', 'goods:siriAccess:desc', '3', '1', '8.00', 'USD', '0', '3', '2018-12-21 10:58:17', '2018-12-21 10:58:17', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('13', '4', '0013', 'goods:iftttAccess', 'icon-com_icon_permission_IFTTT', 'goods:iftttAccess:desc', '3', '1', '8.00', 'USD', '0', '4', '2018-12-21 10:58:17', '2018-12-21 10:58:17', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('14', '4', '0014', 'goods:conradConnectAccess', 'icon-com_icon_permission_Conrad', 'goods:conradConnectAccess:desc', '3', '1', '8.00', 'USD', '0', '5', '2018-12-21 10:58:17', '2018-12-21 10:58:17', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('15', '4', '0015', 'goods:workwithNest', 'icon-com_icon_permission_Nest', 'goods:workwithNest:desc', '3', '1', '8.00', 'USD', '0', '6', '2018-12-21 10:58:17', '2018-12-21 10:58:17', '1', '1');
replace INTO `iot_db_payment`.`goods_info` (`id`, `type_id`, `goods_code`, `goods_name`, `icon`, `description`, `standard`, `standard_unit`, `price`, `currency`, `select_extend_service`, `sort`, `create_time`, `update_time`, `online_status`, `data_status`) VALUES ('16', '4', '0016', 'goods:withPhilipsHue', 'icon-com_icon_permission_Philips', 'goods:withPhilipsHue:desc', '3', '1', '8.00', 'USD', '0', '7', '2018-12-21 10:58:17', '2018-12-21 10:58:17', '1', '1');

