package com.iot.control.space.domain;



import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
@TableName("space")
public class Space extends Model<Space> implements Serializable {

    /**
     * table_name
     */
    public static final String TABLE_NAME = "space";
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.create_time
     *
     * @mbggenerated
     */
    private Date createTime;


    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.user_id
     *
     * @mbggenerated
     */
    @NotNull
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.location_id
     *
     * @mbggenerated
     */
    private Long locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.type
     *
     * @mbggenerated
     */
    private String type;

    private String style;

    private Integer sort;//空间排序

    @NotNull
    private Long tenantId;//租户id

    private Integer defaultSpace;

    private String peopleNum;

    private Long orgId;

    private Integer model;//0普通房间 1会议室

    private Integer timeZoneOffset;

    private Integer seq;//空间下设备序列号
    
    private Long deployId;

    private String meshName;

    private String meshPassword;


    @Override
    protected Serializable pkVal() {
        return this.id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Space space = (Space) o;
        return Objects.equals(id, space.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
