server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://admin:a!23456@192.168.5.20:8761/eureka/
  server:
    enableSelfPreservation: false  # 关闭自我保护模式（缺省为打开）


# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: admin  # 用户名
    password: a!23456   # 用户密码