package com.iot.building.space.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class Space implements Serializable {

    /**
     * table_name
     */
    public static final String TABLE_NAME = "space";
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.location_id
     *
     * @mbggenerated
     */
    private Long locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space.type
     *
     * @mbggenerated
     */
    private String type;

    private String style;

    private Integer sort;//空间排序

    private Long tenantId;//租户id

    private Integer defaultSpace;

    private String orderBy;

    private Long orgId;

    private Integer model;//0普通房间 1会议室

    private Integer seq;//空间下设备序列号
    
    private Long deployId;
    
    public Long getDeployId() {
		return deployId;
	}

	public void setDeployId(Long deployId) {
		this.deployId = deployId;
	}

    public Integer getModel() {
		return model;
	}

	public void setModel(Integer model) {
		this.model = model;
	}

	public Long getOrgId() {
		return orgId;
	}

    public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}

	public Integer getDefaultSpace() {
		return defaultSpace;
	}

	public void setDefaultSpace(Integer defaultSpace) {
		this.defaultSpace = defaultSpace;
	}

	public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.id
     *
     * @return the value of space.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.id
     *
     * @param id the value for space.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.icon
     *
     * @return the value of space.icon
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.icon
     *
     * @param icon the value for space.icon
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.position
     *
     * @return the value of space.position
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.position
     *
     * @param position the value for space.position
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.name
     *
     * @return the value of space.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.name
     *
     * @param name the value for space.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.parent_id
     *
     * @return the value of space.parent_id
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.parent_id
     *
     * @param parentId the value for space.parent_id
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.location_id
     *
     * @return the value of space.location_id
     * @mbggenerated
     */
    public Long getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.location_id
     *
     * @param locationId the value for space.location_id
     * @mbggenerated
     */
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCreateBy() {
		return createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	public Long getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space.type
     *
     * @return the value of space.type
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space.type
     *
     * @param type the value for space.type
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Integer getSeq() { return seq;  }

    public void setSeq(Integer seq) {  this.seq = seq;   }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Space space = (Space) o;
        return Objects.equals(id, space.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
