CREATE TABLE IF NOT EXISTS `iot_db_device`.`generate_module` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`customer` VARCHAR(255) NULL DEFAULT NULL COMMENT '客户',
	`device_type_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '设备类型名字',
	`agreement` VARCHAR(255) NULL DEFAULT NULL COMMENT '协议',
	`g_f` VARCHAR(255) NULL DEFAULT NULL COMMENT '固定标示F',
	`device_type_info` VARCHAR(255) NULL DEFAULT NULL COMMENT '设备类型信息',
	`g_n` VARCHAR(255) NULL DEFAULT NULL COMMENT '固定标示n',
	`code` VARCHAR(255) NULL DEFAULT NULL COMMENT '编码',
	`number` BIGINT(20) NULL DEFAULT NULL COMMENT '序列',
	`create_by` BIGINT(20) NULL DEFAULT NULL,
	`create_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`update_by` BIGINT(20) NULL DEFAULT NULL,
	`update_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`code_number` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=31;
