

USE `iot_db_schedule`;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `qrtz_blob_triggers` DROP FOREIGN KEY `QRTZ_BLOB_TRIGGERS_ibfk_1`;

ALTER TABLE `qrtz_blob_triggers` ADD CONSTRAINT `QRTZ_BLOB_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `qrtz_cron_triggers` DROP FOREIGN KEY `QRTZ_CRON_TRIGGERS_ibfk_1`;

ALTER TABLE `qrtz_cron_triggers` ADD CONSTRAINT `QRTZ_CRON_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `qrtz_simple_triggers` DROP FOREIGN KEY `QRTZ_SIMPLE_TRIGGERS_ibfk_1`;

ALTER TABLE `qrtz_simple_triggers` ADD CONSTRAINT `QRTZ_SIMPLE_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `qrtz_simprop_triggers` DROP FOREIGN KEY `QRTZ_SIMPROP_TRIGGERS_ibfk_1`;

ALTER TABLE `qrtz_simprop_triggers` ADD CONSTRAINT `QRTZ_SIMPROP_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `qrtz_triggers` DROP FOREIGN KEY `QRTZ_TRIGGERS_ibfk_1`;

ALTER TABLE `qrtz_triggers` ADD CONSTRAINT `QRTZ_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) REFERENCES `QRTZ_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DROP INDEX `SCHED_NAME` ON `qrtz_triggers`;

CREATE INDEX `SCHED_NAME` ON `QRTZ_TRIGGERS`(`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) USING BTREE ;

SET FOREIGN_KEY_CHECKS=1;